#%RAML 1.0 DataType

type: object
properties:
  description:
    type: string
    description: "Descripción del sector de actividad."
    required: false
  code:
    type: string
    description: "Código del sector de actividad."
    required: false
