#%RAML 1.0 DataType

type: object
properties:
  code:
    type: string
    description: "Código de la ciudad"
    required: false
  name:
    type: string
    description: "Indica el nombre de la ciudad, normalmente que pertenece a una dirección"
    required: false
