#%RAML 1.0 DataType

type: object
properties:
  code:
    type: string
    description: "Código ISO alfa-2 o alfa-3 válido del país."
    default: All
    required: false
  name:
    type: string
    description: "Nombre del País"
    required: false
