#%RAML 1.0 DataType

type: object
properties:
  productInstanceReference:
    type: string
    description: Indica el identificador del producto
    required: false
  productInstanceReferenceName:
    type: string
    description: Indica el nombre del producto
    required: false
