#%RAML 1.0 DataType

type: object
description: Informacion sobre el estado
properties:
  code:
    type: string
    description: Codigo del estado
    required: false
  name:
    type: string
    description: Nombre del estado
    required: false
