#%RAML 1.0 DataType

type: object
properties:
  requestNumber:
    type: string
    description: Indica el numero de solicitud
    required: false
  branch:
    type: string
    description: Indica el nombre de la sucursal
    required: false
  token:
    type: string
    description: Indica el token
    required: false
  coreType:
    type: string
    description: Indica el core
    required: false
  option:
    type: string
    description: "Opción"
    required: false
  sequence:
    type: string
    description: Secuencia
    required: false
  executionType:
    type: string
    description: "Tipo de ejecución"
    required: false
  requestType:
    type: string
    description: Tipo de pedido
    required: false
  executionDate:
    type: string
    description: "Fecha de ejecución"
    required: false
  userLock:
    type: string
    description: usuario bloqueado
    required: false
  dateLock:
    type: string
    description: Fecha de bloqueo
    required: false
