#%RAML 1.0 Library
usage:


traits:
  responses200: !include traits/responses200.raml
  responses400: !include traits/responses400.raml
  responses401: !include traits/responses401.raml
  responses403: !include traits/responses403.raml
  responses404: !include traits/responses404.raml
  responses408: !include traits/responses408.raml
  responses500: !include traits/responses500.raml